### ISSUE TITLE
Repeating bot

### ISSUE THREAD

**Issue by otteydw** [gsingers/slack-jira-plugin#12]
I'm trying to determine why this would be the case.

If I'm running the bot, it seems to capture my inputs correctly.  I will CTRL-C to close the bot.  Then when I run it again, it returns results for a previously-entered JIRA.

I can't tell if there is any rhyme or reason to it.

**Comment by gsingers** [comment]
Slack APIs resend some events in this case.  I believe it has a small window whereby it gets events in the last X seconds.
