### ISSUE TITLE
Could we see a screen shot?

### ISSUE THREAD

**Issue by pmorch** [gsingers/slack-jira-plugin#20]
I'm new to Slack, and haven't yet tried `slack-jira-plugin`. It would be really nice if one could get an idea of what it does by seeing it in action in a screenshot, before I go through hoops of installing it.. ;-)

> Automatically append a link to a message whenever there is a mention of a JIRA issue in the message

I'm hoping that it'll look somewhat like this:
![bugbot screeshot](https://gigaom.com/wp-content/uploads/sites/1/2014/02/slack-desktop-integrations.png)

Is it so that if I mention BUG-4345 in any slack converstation, the metadata (title) is extraced and shown?

I'd love to see a screenshot to help me understand what `slack-jira-plugin` actually is! :-)

**Comment by pmorch** [comment]
I also found [shaunburdick/slack-jirabot: Slack Bot to listen for JIRA tickets and enhance conversation](https://github.com/shaunburdick/slack-jirabot) which looks like the screenshot below. Assuming that is the only thing slack-jirabot does, how does this project compare to slack-jirabot featurewise?

![example.png (PNG Image, 1244 × 864 pixels) - Scaled (89%)](https://raw.githubusercontent.com/shaunburdick/slack-jirabot/master/doc/img/example.png)

**Comment by gsingers** [comment]
@pmorch Yeah, it does similar things.  It simply looks at messages and will add links and other information to the actual ticket to the message stream.  The display is somewhat configurable and looks similar to what you posted.
