### ISSUE TITLE
[Feature] Private JIRA projects (No data)

### ISSUE THREAD

**Issue by crash83k** [gsingers/slack-jira-plugin#25]
This is a slick little project. I think one thing it needs is a way to add an authentication component to read private JIRA projects. 

If I have time, I might be able to add it and create a PR for it. Unless this is already on the roadmap. #

**Comment by gsingers** [comment]
Hi @crash83k,

Unless I'm not understanding correctly, it already does.  See the sample config.  You can pass in JIRA credentials to connect to private JIRA repos.  I'll close for now, but feel free to reopen if I'm missing what you mean.

**Comment by crash83k** [comment]
You're right. I guess I was more or less looking for a way to use tokens (instead of displaying user/pass in plain text). But I started looking through JIRA's settings and couldn't find anywhere that allowed me to create an OAuth token anymore. I'm wondering if they moved it or removed it.

Thanks. I'll keep looking around. But I guess I'll just end up creating a view-only user.
