### ISSUE TITLE
Installation instructions need clarity

### ISSUE THREAD

**Issue by stewsnooze** [gsingers/slack-jira-plugin#26]
Hi, 

In the installation instructions I see it asks for a token and points at a URL on Slack.com

```
  token: 'XXXX-XXXXXXXXXX-XXXXXXXXXX-XXXXXXXXXX-XXXXXX', // https://api.slack.com/web
```

However when going to Slack I can create apps which I assume is correct

I assume this doesn't use oauth, perhaps a bot user?

On the left hand side of this graphic we see options for an app like Bot users, app credentials e.t.c.

What do we do?  I'm happy to make this a Pull Request when I figure out how to actually install it to improve first time installation if you could help?

![slack_api__applications___slack](https://cloud.githubusercontent.com/assets/196643/17782417/439bc35e-656b-11e6-8a12-76a1ef5d6b6a.png)

**Comment by gsingers** [comment]
Hi @stewsnooze 

Hmm, perhaps Slack has changed their docs.  I think they are now calling them Tester tokens: https://api.slack.com/docs/oauth-test-tokens.  I haven't verified, but it's likely the case that by registering your app, you can also get a token: https://api.slack.com/web

-Grant

**Comment by Tom-Gray** [comment]
Maybe I'm misreading the question, but it seems like you need to create a bot token. You can create a bot for the RTM API here - https://<yourcompany>.slack.com/apps/build/custom-integration

That will give you a bot user and importantly, a token that you need to authenticate with.
